### ISSUE TITLE
Allow fractional vote counts?

### ISSUE THREAD

**Issue by simberaj** [electorama/abif#10]
Do we want to allow non-integer vote counts in ABIF? E.g. this

    1.5: A>B=C

would be a valid ABIF line.

If so, do we want decimal numbers, or even fractions such as

    1/3: A>B=C

?

**Comment by robla** [comment]
Oh, the wily fractional vote!  We all know how difficult it is to express fractions (like `1/3`) using decimal numbers.

I don't know the answer.  My gut tells me the best answer is to _maybe_ allow for decimal notation (e.g `0.333: A>B=C`) and then maybe encourage specific implementations that want to allow for vote splitting that isn't expressed cleanly in decimal notation to have a custom "vote denominator" field in the header.  But I'm not sure.  I think initial implementations (like anything that I write) is going to only deal with whole votes that can be expressed as integers.

**Comment by brainbuz** [comment]
I recommend leaving this for a later time. 

```
In ABIF 1.0 the count must be an integer. If a need is
demonstrated for fractional and decimal count values, 
this will need to be addressed by a later revision.
```

**Comment by simberaj** [comment]
Agreed, closing this. I'll update the votelib code accordingly.
